### ISSUE TITLE
When saving retail key data from clipboard, no file is created

### ISSUE THREAD

**Issue by cspencer49519** [AcK77/AmiiBomb-uino#7]
I already made you aware of this on gba, but wanted to open a formal issue. When copying the needed key data to the clipboard you are presented with a dialog box in amiboomb-uino that asks you if you want to save this data to a file, but, when you attempt to save the data, it is not saved. The dialog box just continues to popup.

**Comment by AcK77** [comment]
Thanks for the report, I'm gonna see what's happen here ;)!

**Comment by Zombuino** [comment]
I have same issue on 0.2 and 0.3 versions.   Could this be related to the Unhandled Exception error I am receiving: #13 ?

**Comment by kokkie20** [comment]
As far as i could see there is no function to save the copied clipboard to file... Still working on other things to fix first ;) 
@AcK77 @cspencer49519 
Fixed the saving key part 👍

**Comment by wachpwnski** [comment]
I'm still getting this issue on a new Windows 10 install. It's not actually saving a file, but I see it in my recent files.

In addition I created the key with HxD, and it's saying that it's an incorrect key.
